Vagrant.configure("2") do |config|
  config.ssh.private_key_path = "#{ENV['HOME']}/.vagrant/insecure_private_key"
  config.ssh.insert_key = false
  config.vm.box = "bento/ubuntu-22.04"
  # config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.synced_folder "../www", "/var/www", SharedFoldersEnableSymlinksCreate: false, mount_options: ["dmode=777,fmode=777"]
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "1024"
  # end
  config.vm.provision "file", source: "src/.", destination: "/tmp/vagrant-shell-scripts/"
  config.vm.provision "shell", path: "src/bootstrap", upload_path: "/tmp/vagrant-shell-scripts/vagrant-shell"
end
